// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Cae_PictureTouch","status":true,"description":"v1.6 - Run events or scripts when pictures are touched/hovered.","parameters":{"Minimum Opacity":"1","Minimum Opacity For All":"false","Unbind on Show":"false","Unbind on Erase":"true","Disable on Trigger":"false","Add Save Data":"true","Always Update Hover":"false","Picture ID Variable":"0"}},
{"name":"GALV_ChoicePauseMZ","status":true,"description":"(v.1.0) Prevent the player from accidentally selecting a choice by adding a pause","parameters":{"Pause Time":"20"}},
{"name":"GALV_VisualNovelChoicesMZ","status":true,"description":"(v.1.0) Changes how the \"Choice\" message boxes display to appear more like visual novels.","parameters":{"Command Width":"350","Command Height":"70","Always Middle":"true","Message Gap":"45","Disabled Button":"3"}},
{"name":"MOG_PictureEffects","status":true,"description":"(v1.1) O plugin permite animar as imagens.","parameters":{}},
{"name":"Cae_ChoiceShuffle","status":true,"description":"v1.0 - Randomly reorder Show Choices when shuffle mode is on.","parameters":{"Default Shuffle":"true","Add Save Data":"false","--- Advanced ---":"","Save Property Name":"ChoiceShuffle"}},
{"name":"telainicialcustomizada","status":true,"description":"Tela inicial customizada estilo VN para RPG Maker MZ","parameters":{"backgroundImage":"title_bg","newGameImage":"btn_newgame","newGameHoverImage":"btn_newgame_hover","loadGameImage":"btn_load","loadGameHoverImage":"btn_load_hover","newGameX":"0","newGameY":"424","loadGameX":"0","loadGameY":"504"}},
{"name":"menupause","status":true,"description":"Adiciona um menu de pausa customizável.","parameters":{"menuBackground":"pause_bg","buttonBackground":"btn_bg","buttonHoverBackground":"btn_bg_hover","fontSize":"26","fontFace":"rmmz-mainfont","buttonSpacing":"70","pauseTitle":"  ","titleFontSize":"48","titleOffsetY":"-260","pauseButtonImage":"botao_menu","pauseButtonHoverImage":"botao_menu_hover","pauseButtonX":"752","pauseButtonY":"16","pauseButtonSwitch":"18"}},
{"name":"saveload","status":true,"description":"Sistema Save/Load VN Visual Custom","parameters":{"saveBackground":"save_bg","slotImage":"save_slot","slotHoverImage":"save_slot_hover","closeButtonImage":"save_close","closeButtonHoverImage":"save_close_hover","nextButtonImage":"save_next","prevButtonImage":"save_prev","fontFace":"rmmz-mainfont","fontSize":"18","dayVariableId":"12"}},
{"name":"VN_AutoColorWords","status":true,"description":"Colore automaticamente palavras específicas.","parameters":{"coloredWords":"[\"{\\\"word\\\":\\\"   Você\\\",\\\"colorId\\\":\\\"2\\\"}\"]"}},
{"name":"MOG_TouchAnimation","status":true,"description":"(v1.0) Apresenta uma animação de toque.","parameters":{"File Name":"TouchParticles","Animation":"Fireworks","Number of Particles":"10","X-Axis Offset":"0","Y-Axis Offset":"0","Blend Mode":"Normal","Duration":"10","Fade Speed":"20","Random Tone":"true"}},
{"name":"PictureTextureWarmupMZ","status":true,"description":"Warm up picture textures on GPU before Show Picture","parameters":{}}
];
